### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by joey082** [MaxThakurCodes/friend-finder#1]
**Describe the bug**
Under the id of who you are reporting id field has tag

**To Reproduce**
1. Run 'report'
2. Use this argument 'normally but instead of id ping a user '
3. See error in embed

**Expected behavior**
The id field for who you are reporting should include the id not a ping

**Screenshots**

**Please complete the following information:**
 V. 0.0.1
**Additional context**

**Comment by MaxThakurCodes** [comment]
Hey there, could you possibly fill in the `To Reproduce` section, and also Expected behavior as I don't know what to rework if I don't have any errors/bugs to edit?

**Comment by MaxThakurCodes** [comment]
@all-contributors please add joey082 for bug

**Comment by MaxThakurCodes** [comment]
@all-contributors please add joey082 for bugs

**Comment by MaxThakurCodes** [comment]
@joey082 I've updated the bug you reported in your request. Thanks for the help, have a good day or night!

**Comment by MaxThakurCodes** [comment]
@all-contributors please add MaxThakurCodes for bugs, code, projectManagement, doc, design, ideas, maintenance, and questions.
